name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Print conteúdo do arquivo hello.txt
      run: cat hello.txt

    - name: Build da imagem Docker
      run: |
        docker build -t hello-jenkins:v1 .

    # (Opcional) Adicione push pro Docker Hub aqui depois
